### ISSUE TITLE
Make the host the server listens on configurable

### ISSUE THREAD

**Issue by yashshah1** [ramlmn/serv#16]
Allow the server to just listen on `127.0.0.1` or a user-specified IP which can be configured by the CLA

https://github.com/ramlmn/serv/blob/aee38bc2d451d7c0aedfcede1f4e1a66279e0ebe/bin/serv.js#L113

**Comment by r0mflip** [comment]
Thanks for letting us know @yashshah1 

We have a many plans for `serv` coming on the way and a few which are overdue. Will include in the list.

**Comment by yashshah1** [comment]
Are you open for contributors?

**Comment by r0mflip** [comment]
Please feel free to raise a PR 😃
